model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_top_k: 10
  monitor: val/loss
  mode: min

  auto_insert_metric_name: False
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  filename: "epoch-{epoch:03d}-{val/loss:.4f}"
